export const userList = [
    {
        email: "IreneJFrazier@rhyta.com",
        first: "Irene",
        last: "Frazier",
        status: "undergrad"
    }, { 
        email: "augustus77@amazonshopzen.com",
        first: "Letitia",
        last: "Kautzer",
        status: "faculty"
    }, { 
        email: "lavon14@gmail.com",
        first: "Adolf",
        last: "Weimann",
        status: "scholar"
    }, { 
        email: "sbogisich@bizimalem-support.de",
        first: "Rubie",
        last: "Jast",
        status: "non-member"
    }, { 
        email: "shakira.moen@vozvrmfovklad.xyz",
        first: "Rosie",
        last: "Tromp",
        status: "undergrad"
    }, {
        email: "shyann.stehr@bizimalem-support.de",
        first: "Joel",
        last: "Conner",
        status: "nt-faculty"
    }, { 
        email: "quitzon.granvil@mayimed.com",
        first: "Laurence",
        last: "Funk",
        status: "scholar"
    }, { 
        email: "romaguera.virgi@lolibox.ml",
        first: "Shawna",
        last: "Dietrich",
        status: "non-member"
    }, { 
        email: "jovanny73@floridaharvard.com",
        first: "Shana",
        last: "Prohaska",
        status: "graduate"
    }, { 
        email: "clark28@napkin.edu",
        first: "Lavern",
        last: "Prosacco",
        status: "postdoc"
    }, { 
        email: "donaldjtrump@trump.com",
        first: "Donald",
        last: "Trump",
        status: "undergrad"
    }, {
        email: "gb303@gatech.edu",
        first: "George",
        last: "Burdell",
        status: "graduate"
    }, {
        email: "joebiden@democrat.org",
        first: "Joe",
        last: "Biden",
        status: "scholar"
    }, {
        email: "jason_zhen@gatech.edu",
        first: "Jason",
        last: "Jia",
        status: "nt-faculty"
    }
];
