export const SET_LOGIN = '/app/SET_LOGIN'
export const SET_CURR_PAGE = '/app/SET_CURR_PAGE'
export const SET_PROFILE = '/app/SET_PROFILE'
export const CLEAR_CART = '/app/CLEAR_CART'
export const ADD_TO_CART = '/app/ADD_TO_CART'
export const SET_ADMIN = '/app/SET_ADMIN'